version: '3'

services:

  broker:
    image: redis

  scheduler:
    build: .
    command: ['mixedcontent']
    depends_on:
      - broker
      - worker
    links:
      - broker
    volumes:
      - ./mixedcontent:/home/seluser/mixedcontent
      - ./scripts:/home/seluser/scripts
      - ./setup.py:/home/seluser/setup.py
      - ./data:/home/seluser/data

  worker:
    build: .
    command: ['celery', '-A', 'mixedcontent.distributed', 'worker', '-l', 'ERROR', '-c', '1']
    depends_on:
      - broker
    dns:
      - 8.8.8.8
      - 1.1.1.1
    links:
      - broker
    volumes:
      - ./mixedcontent:/home/seluser/mixedcontent
      - ./scripts:/home/seluser/scripts
      - ./setup.py:/home/seluser/setup.py
      - ./data:/home/seluser/data
