version: '3'

services:

  broker:
    image: redis

  results:
    image: redis

  scheduler:
    build: .
    command: ['mixedcontent']
    depends_on:
      - broker
      - results
      - worker
    links:
      - broker
      - results
    volumes:
      - ./mixedcontent:/home/seluser/mixedcontent
      - ./scripts:/home/seluser/scripts
      - ./setup.py:/home/seluser/setup.py
      - ./domains.cfg:/home/seluser/domains.cfg
      - ./results:/home/seluser/results

  worker:
    build: .
    command: ['celery', '-A', 'mixedcontent.distributed', 'worker', '-l', 'INFO']
    depends_on:
      - broker
      - results
    links:
      - broker
      - results
    volumes:
      - ./mixedcontent:/home/seluser/mixedcontent
      - ./scripts:/home/seluser/scripts
      - ./setup.py:/home/seluser/setup.py
      - ./domains.cfg:/home/seluser/domains.cfg
