#!/usr/bin/env python3

import socket
import time
from subprocess import Popen

from celery.result import ResultBase
from mixedcontent.distributed import collect_urls


def start_selenium_server():
    Popen(['/opt/bin/entry_point.sh'])
    started = False
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    start_time = time.time()
    started = False
    while not started:
        started = sock.connect_ex(('127.0.0.1', 4444)) == 0
        if time.time() - start_time > 10:
            raise IOError('Could not connect to Selenium server.')


if __name__ == '__main__':
    sitemaps = set()
    with open('sitemaps.cfg', 'r') as f:
        for line in f:
            sitemaps.add(line.strip())
    result = collect_urls.delay(list(sitemaps))
    with open('results/results.txt', 'w') as f:
        for r in result.collect():
            if not isinstance(r, (ResultBase, tuple)):
                f.write(r)
